# Verify-UTREx-Prerequisites.ps1
# Build environment verification script for UTREx_SIF_VRF
# Generated by Reversa Visor on 2026-05-13
# Usage: .\Verify-UTREx-Prerequisites.ps1 [-Verbose] [-Fix]

[CmdletBinding()]
param(
    [switch]$Fix,        # Attempt to auto-fix resolvable issues
    [switch]$SkipSQL,    # Skip SQL Server checks (if no SQL access)
    [string]$RepoRoot = $PSScriptRoot
)

$ErrorActionPreference = 'Continue'
$issues = @()
$warnings = @()
$passes = @()

function Write-Pass  { param($msg) Write-Host "  [PASS] $msg" -ForegroundColor Green;  $script:passes  += $msg }
function Write-Warn  { param($msg) Write-Host "  [WARN] $msg" -ForegroundColor Yellow; $script:warnings += $msg }
function Write-Fail  { param($msg) Write-Host "  [FAIL] $msg" -ForegroundColor Red;    $script:issues  += $msg }
function Write-Info  { param($msg) Write-Host "  [INFO] $msg" -ForegroundColor Cyan }
function Write-Check { param($msg) Write-Host "`n=== $msg ===" -ForegroundColor White }

Write-Host "`nUTREx_SIF_VRF — Build & Deployment Prerequisites Check" -ForegroundColor Magenta
Write-Host "Repo root: $RepoRoot"
Write-Host "Date:      $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n"

# ── 1. Repo Structure ──────────────────────────────────────────────────────────
Write-Check "1. Repository Structure"

$expectedDirs = @(
    "UtahPublicEd.VRF",
    "UtahPublicEd.VRF\UtahPublicEd.VRF.MockSisAgent",
    "UTREx_VRF_ReportCollector\Manifests",
    "UTREx_VRF_ReportCollector\Manifests\tools\EmbedManifest",
    "UTREx_VRF_ReportCollector\Scripts"
)

foreach ($dir in $expectedDirs) {
    $fullPath = Join-Path $RepoRoot $dir
    if (Test-Path $fullPath) {
        Write-Pass "Directory exists: $dir"
    } else {
        Write-Fail "Missing directory: $dir"
    }
}

$expectedFiles = @(
    "UtahPublicEd.VRF\UtahPublicEd.VRF.MockSisAgent\Program.cs",
    "UtahPublicEd.VRF\UtahPublicEd.VRF.MockSisAgent\PublishingAgent.cs",
    "UtahPublicEd.VRF\UtahPublicEd.VRF.MockSisAgent\agent.cfg",
    "UtahPublicEd.VRF\UtahPublicEd.VRF.MockSisAgent\appsettings.json",
    "UTREx_VRF_ReportCollector\Manifests\UTREx_Definition.xml",
    "UTREx_VRF_ReportCollector\Manifests\UTREx_Wrapper.xml",
    "UTREx_VRF_ReportCollector\Scripts\Cactus to UTREx.VRF_RC sync.sql"
)

foreach ($file in $expectedFiles) {
    $fullPath = Join-Path $RepoRoot $file
    if (Test-Path $fullPath) {
        Write-Pass "File exists: $file"
    } else {
        Write-Fail "Missing file: $file"
    }
}

# ── 2. Git Submodules ──────────────────────────────────────────────────────────
Write-Check "2. Git Submodules"

$submodules = @("OpenADK-csharp", "SifCommonFramework-dotNet")
foreach ($sub in $submodules) {
    $subPath = Join-Path $RepoRoot $sub
    if (-not (Test-Path $subPath)) {
        Write-Fail "Submodule directory missing: $sub"
        if ($Fix) {
            Write-Info "Attempting: git submodule update --init --recursive"
            Push-Location $RepoRoot
            git submodule update --init --recursive
            Pop-Location
        } else {
            Write-Info "Run: git submodule update --init --recursive"
        }
    } else {
        # Check if populated (not just empty directory)
        $csprojFiles = Get-ChildItem -Path $subPath -Filter "*.csproj" -Recurse -ErrorAction SilentlyContinue
        if ($csprojFiles.Count -gt 0) {
            Write-Pass "Submodule populated: $sub ($($csprojFiles.Count) .csproj files)"
        } else {
            Write-Fail "Submodule directory exists but appears empty: $sub"
            Write-Info "Run: git submodule update --init --recursive"
        }
    }
}

# ── 3. .NET Framework Build Tools ─────────────────────────────────────────────
Write-Check "3. .NET Framework Build Tools"

# Check for .NET SDK
$dotnetVersion = & dotnet --version 2>$null
if ($LASTEXITCODE -eq 0) {
    Write-Pass ".NET SDK found: $dotnetVersion"
} else {
    Write-Fail ".NET SDK not found — install from https://dotnet.microsoft.com/download"
}

# Check for .NET Framework 4.8.1 reference assemblies (required for net481 target)
$frameworkPath = "${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8.1"
if (Test-Path $frameworkPath) {
    Write-Pass ".NET Framework 4.8.1 reference assemblies found"
} else {
    $v48Path = "${env:ProgramFiles(x86)}\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8"
    if (Test-Path $v48Path) {
        Write-Warn ".NET Framework 4.8 found (4.8.1 preferred); build may succeed"
    } else {
        Write-Fail ".NET Framework 4.8.1 reference assemblies not found"
        Write-Info "Install .NET Framework 4.8.1 Developer Pack from Microsoft"
    }
}

# Check for MSBuild (Visual Studio or Build Tools)
$msbuildPaths = @(
    "${env:ProgramFiles}\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe",
    "${env:ProgramFiles}\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\MSBuild.exe",
    "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe",
    "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe"
)

$msbuildFound = $false
foreach ($msbuild in $msbuildPaths) {
    if (Test-Path $msbuild) {
        Write-Pass "MSBuild found: $msbuild"
        $msbuildFound = $true
        break
    }
}
if (-not $msbuildFound) {
    $msbuildInPath = Get-Command msbuild -ErrorAction SilentlyContinue
    if ($msbuildInPath) {
        Write-Pass "MSBuild found in PATH: $($msbuildInPath.Source)"
    } else {
        Write-Warn "MSBuild not found — needed for .NET Framework projects; install Visual Studio or Build Tools 2022"
    }
}

# ── 4. NuGet Packages ──────────────────────────────────────────────────────────
Write-Check "4. NuGet Package Restore"

$slnFile = Join-Path $RepoRoot "UtahPublicEd.VRF\UtahPublicEd.VRF.sln"
if (Test-Path $slnFile) {
    Write-Info "Attempting package restore for: $slnFile"
    $restoreOutput = & dotnet restore $slnFile 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-Pass "NuGet restore succeeded"
    } else {
        Write-Fail "NuGet restore failed — check network access and NuGet feed configuration"
        if ($VerbosePreference -eq 'Continue') { Write-Host $restoreOutput }
    }
} else {
    Write-Warn "Solution file not found at expected path: $slnFile"
}

# ── 5. Manifest Files ──────────────────────────────────────────────────────────
Write-Check "5. Manifest Files"

$defPath  = Join-Path $RepoRoot "UTREx_VRF_ReportCollector\Manifests\UTREx_Definition.xml"
$wrapPath = Join-Path $RepoRoot "UTREx_VRF_ReportCollector\Manifests\UTREx_Wrapper.xml"

foreach ($xmlFile in @($defPath, $wrapPath)) {
    if (Test-Path $xmlFile) {
        try {
            $xml = [xml](Get-Content $xmlFile -Raw)
            Write-Pass "Valid XML: $(Split-Path $xmlFile -Leaf)"
        } catch {
            Write-Fail "Invalid XML in $(Split-Path $xmlFile -Leaf): $_"
        }
    } else {
        Write-Fail "Manifest file not found: $xmlFile"
    }
}

# Check manifest version and code
if (Test-Path $defPath) {
    $defXml = [xml](Get-Content $defPath -Raw)
    $manifestCode = $defXml.SelectSingleNode("//*[local-name()='ManifestCode']")?.InnerText
    $version      = $defXml.DocumentElement?.GetAttribute("version")

    if ($manifestCode) {
        Write-Pass "ManifestCode: $manifestCode"
        if ($manifestCode -match '^\d{4}[A-Z]+$') {
            Write-Pass "ManifestCode format valid (YYYYTYPE)"
        } else {
            Write-Warn "ManifestCode '$manifestCode' does not match expected format YYYYTYPE"
        }
    } else {
        Write-Warn "ManifestCode element not found in Definition.xml"
    }
    if ($version) { Write-Pass "Manifest version: $version" }
}

# ── 6. SQL Prerequisites (optional) ───────────────────────────────────────────
if (-not $SkipSQL) {
    Write-Check "6. SQL Server Prerequisites"
    Write-Info "Checking for sqlcmd availability..."

    $sqlcmd = Get-Command sqlcmd -ErrorAction SilentlyContinue
    if ($sqlcmd) {
        Write-Pass "sqlcmd found: $($sqlcmd.Source)"

        Write-Info "To check SQL Server version and linked server, run manually:"
        Write-Info "  sqlcmd -S <server> -Q `"SELECT @@VERSION`""
        Write-Info "  sqlcmd -S <server> -Q `"SELECT name FROM sys.servers WHERE is_linked = 1`""
        Write-Warn "SQL Server version check requires active connection — skipped in automated check"
        Write-Warn "Manually verify: SQL Server 2019 or later required (see decisions.json)"
    } else {
        Write-Warn "sqlcmd not found in PATH — install SQL Server tools for CLI access"
    }

    # Check sync SQL file
    $syncSql = Join-Path $RepoRoot "UTREx_VRF_ReportCollector\Scripts\Cactus to UTREx.VRF_RC sync.sql"
    if (Test-Path $syncSql) {
        $sqlContent = Get-Content $syncSql -Raw
        if ($sqlContent -match 'MERGE') {
            Write-Pass "Sync SQL contains MERGE statements"
        }
        if ($sqlContent -match '\[CACTUS\]') {
            Write-Pass "Sync SQL references [CACTUS] linked server"
        }
        if ($sqlContent -match "OWNER\s*=\s*'sa'|OWNER\s*=\s*N'sa'") {
            Write-Fail "SECURITY: SQL script references 'sa' as job owner — must be changed to service account (see decisions.json D-003)"
        }
    }
} else {
    Write-Info "SQL checks skipped (-SkipSQL flag)"
}

# ── 7. Spec Files ──────────────────────────────────────────────────────────────
Write-Check "7. Reversa Specification Files"

$specFiles = @(
    "_reversa_sdd\INDEX.md",
    "_reversa_sdd\IMPLEMENTATION-ROADMAP.md",
    "_reversa_sdd\CHECKLISTS.md",
    "_reversa_sdd\manifest.xsd",
    "_reversa_sdd\MockSisAgent\requirements.md",
    "_reversa_sdd\MockSisAgent\tasks.md",
    "_reversa_sdd\CactusSync_SQL\tasks.md",
    "_reversa_sdd\VRF_Manifests\requirements.md",
    "_reversa_sdd\diagrams\dependency-graph.md",
    "_reversa_sdd\diagrams\data-flow-sequence.md",
    "_reversa_sdd\diagrams\erd-vrf-rc.md"
)

$specCount = 0
foreach ($spec in $specFiles) {
    if (Test-Path (Join-Path $RepoRoot $spec)) {
        $specCount++
    } else {
        Write-Warn "Spec file missing: $spec (re-run Reversa to regenerate)"
    }
}
Write-Pass "$specCount / $($specFiles.Count) expected spec files present"

# Check decisions.json
$decisionsPath = Join-Path $RepoRoot ".reversa\decisions.json"
if (Test-Path $decisionsPath) {
    $decisions = Get-Content $decisionsPath -Raw | ConvertFrom-Json
    $undecided = @($decisions.decisions | Where-Object { $null -eq $_.decision })
    if ($undecided.Count -eq 0) {
        Write-Pass "All architectural decisions recorded in decisions.json"
    } else {
        Write-Warn "$($undecided.Count) decisions still pending in .reversa/decisions.json:"
        $undecided | ForEach-Object { Write-Warn "  - $($_.id): $($_.question_ref)" }
    }
} else {
    Write-Warn ".reversa/decisions.json not found — run Reversa framework to generate"
}

# ── Summary ────────────────────────────────────────────────────────────────────
Write-Host "`n══════════════════════════════════════════" -ForegroundColor White
Write-Host "  VERIFICATION SUMMARY" -ForegroundColor White
Write-Host "══════════════════════════════════════════" -ForegroundColor White
Write-Host "  PASS:    $($passes.Count)" -ForegroundColor Green
Write-Host "  WARN:    $($warnings.Count)" -ForegroundColor Yellow
Write-Host "  FAIL:    $($issues.Count)" -ForegroundColor Red
Write-Host "══════════════════════════════════════════`n" -ForegroundColor White

if ($issues.Count -gt 0) {
    Write-Host "CRITICAL ISSUES (must fix before Phase 1):" -ForegroundColor Red
    $issues | ForEach-Object { Write-Host "  • $_" -ForegroundColor Red }
}
if ($warnings.Count -gt 0) {
    Write-Host "`nWARNINGS (review before Phase 1):" -ForegroundColor Yellow
    $warnings | ForEach-Object { Write-Host "  • $_" -ForegroundColor Yellow }
}

if ($issues.Count -eq 0 -and $warnings.Count -eq 0) {
    Write-Host "✅ All checks passed — environment ready for Phase 1 implementation" -ForegroundColor Green
    exit 0
} elseif ($issues.Count -eq 0) {
    Write-Host "⚠️  Warnings found — review before proceeding" -ForegroundColor Yellow
    exit 1
} else {
    Write-Host "❌ Critical issues found — resolve before Phase 1 implementation" -ForegroundColor Red
    exit 2
}
