#!/usr/bin/env python3
"""
AXiomEngine Release Notes Generator (v1.5.0)
========================================
Synthesizes release forensics into authoritative documentation.
Requires Release Verifier JSON as input for truthfulness.
"""
import json
import argparse
from datetime import datetime
from pathlib import Path

TEMPLATE = """# AXiomEngine Governance {version} Release Notes

**Date**: {date}
**Status**: {status}
**Baseline Integrity**: {integrity}

## Executive Summary
{summary}

## Workstream Accomplishments
{workstreams}

## Operational Commands
{commands}

## Verification Proof
- **Total Tests**: {tests_passed}/{tests_expected}
- **Baseline Drift**: {drift}
- **Required Files**: {inventory}
- **Release Evidence ID**: {evidence_id}

---
*Generated by AXiomEngine Release Engineering (v1.5.0)*
"""

def generate_release_notes(project_root, verifier_json_path=None, version="v1.5.0"):
    root = Path(project_root).absolute()
    
    # Truth Discovery: Load verifier data if available
    v_data = {}
    if verifier_json_path:
        v_path = Path(verifier_json_path)
        if v_path.exists():
            try:
                v_data = json.loads(v_path.read_text())
            except Exception as e:
                print(f"⚠️ Warning: Could not parse verifier JSON: {e}")
    
    # 1. Status and Integrity Truth
    is_stable = v_data.get("release_status") == "STABLE"
    status = "STABLE" if is_stable else "DRAFT / UNVERIFIED"
    
    drift_detected = v_data.get("baseline_drift_detected", True)
    integrity = "VERIFIED (v1.3.1 Baseline)" if not drift_detected else "⚠️ DRIFT DETECTED"
    
    tests_passed = v_data.get("tests_observed", 0) if v_data.get("tests_passed") else 0
    tests_expected = v_data.get("tests_expected", "UNKNOWN")
    
    inventory = "COMPLETE" if v_data.get("required_files_present") else "❌ MISSING FILES"
    drift = "None Detected" if not drift_detected else "Baseline Mismatch detected"
    
    # 2. Executive Summary
    summary = "This release hardens the AXiomEngine governance stack through release engineering, CI automation, and forensic verification. It ensures that the audit-frozen v1.3.1 core remains integral across all environments."
    if not is_stable:
        summary = "⚠️ WARNING: This release has not passed all stabilization gates. It is provided for review purposes only."

    workstreams = [
        "- **Workstream 1**: Release Verification Foundation (Aligned with Contract)",
        "- **Workstream 2**: GitHub Actions CI Automation",
        "- **Workstream 3**: Cryptographic Release Signing (DEFERRED to v1.6.0)",
        "- **Workstream 4**: Timestamped Audit Bundle Export (with Embedded Manifest)",
        "- **Workstream 5**: Unified CLI Packaging Entrypoints",
        "- **Workstream 6**: Contract Drift Detection (Expanding Registry)"
    ]
    
    commands = [
        "### Verify Release\n`python3 scripts/release_verifier.py --project-root .`",
        "### Export Audit Bundle\n`python3 scripts/governance_cli.py audit-bundle`",
        "### View Health Summary\n`python3 scripts/governance_cli.py summary`"
    ]
    
    # Create the notes
    notes = TEMPLATE.format(
        version=version,
        date=datetime.now().strftime("%Y-%m-%d"),
        status=status,
        integrity=integrity,
        summary=summary,
        workstreams="\n".join(workstreams),
        commands="\n\n".join(commands),
        tests_passed=tests_passed,
        tests_expected=tests_expected,
        drift=drift,
        inventory=inventory,
        evidence_id=f"RE-EVID-{datetime.now().strftime('%Y%m%d%H%M')}" if is_stable else "UNVERIFIED"
    )
    
    out_path = root / "docs/audit" / f"RELEASE_NOTES_{version.replace('.', '_')}.md"
    out_path.write_text(notes)
    print(f"✨ Release Notes generated: {out_path}")
    if not is_stable:
        print("⚠️  Warning: Release Notes marked as DRAFT / UNVERIFIED due to lack of stable verifier evidence.")
    return out_path

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--verifier-json", help="Path to release_verifier.py JSON output")
    parser.add_argument("--version", default="v1.5.0")
    args = parser.parse_args()
    
    generate_release_notes(args.project_root, args.verifier_json, args.version)
