#!/usr/bin/env python3
import os
import re
import json
from pathlib import Path

ROOT_DIR = Path("/mnt/UBUNTU_8TB/Projects/axiomengine")
CATALOG_DIR = ROOT_DIR / "data" / "catalog"

def get_real_char_count(abs_path):
    if not abs_path.exists():
        return 0
    try:
        content = abs_path.read_text(errors='ignore')
        real_chars = re.sub(r'\s', '', content)
        return len(real_chars)
    except:
        return 0

def get_line_count(abs_path):
    if abs_path.exists():
        try:
            return sum(1 for _ in abs_path.open('r', errors='ignore'))
        except:
            return 0
    return 0

def parse_catalog():
    stats = {} # code_file -> { rules: set, context_chars: int, test_chars: int }
    
    # Iterate through all subdirectories in catalog
    for folder in CATALOG_DIR.iterdir():
        if folder.is_dir():
            for rule_file in folder.glob("*.json"):
                try:
                    with open(rule_file, "r") as f:
                        data = json.load(f)
                    
                    rule_id = data.get("id")
                    context_chars = get_real_char_count(rule_file)
                    
                    # Check interfaces for physical files
                    for intf in data.get("interfaces", {}).values():
                        if intf.get("status") == "Implemented" and "path_of_file" in intf:
                            code_file = intf["path_of_file"]
                            if code_file not in stats:
                                stats[code_file] = {'rules': set(), 'context_chars': 0, 'test_chars': 0}
                            stats[code_file]['rules'].add(rule_id)
                            stats[code_file]['context_chars'] += context_chars
                    
                    # Check tests
                    tdd = data.get("tdd_governance", {})
                    if tdd.get("test_verification", {}).get("exists"):
                        test_path = tdd["test_verification"]["path"]
                        # We don't have a specific code file mapping for tests here, 
                        # so we just track them if we find a match
                except:
                    continue
    return stats

def scan_all_code_files():
    code_files = []
    exclude_dirs = {'data', 'cache', '.git', '.context', 'node_modules', 'scratch'}
    for root, dirs, files in os.walk(ROOT_DIR):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        for f in files:
            if f.endswith(('.py', '.ts', '.md', '.json')) and "-context" not in f:
                code_files.append(os.path.relpath(os.path.join(root, f), ROOT_DIR))
    return code_files

def main():
    print("📊 Generating AXiomEngine Governance Report...")
    stats = parse_catalog()
    all_code_files = scan_all_code_files()
    
    output_path = ROOT_DIR / "AXIOMENGINE_GOVERNANCE_REPORT.md"
    
    with open(output_path, 'w') as f:
        f.write("# AXiomEngine: Governance & PDD Depth Report\n\n")
        f.write("> [!IMPORTANT]\n")
        f.write("> This report is generated by the Axiomatic Governance Engine (Trifecta Swarm).\n\n")
        
        f.write("| Code File | Lines | Rules | Code (Real) | Context (Real) | Ratio | Status |\n")
        f.write("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n")
        
        total_code = 0
        total_context = 0
        
        for cf in sorted(all_code_files):
            abs_cf = ROOT_DIR / cf
            line_count = get_line_count(abs_cf)
            real_code = get_real_char_count(abs_cf)
            
            data = stats.get(cf, {'rules': set(), 'context_chars': 0})
            rule_count = len(data['rules'])
            real_context = data['context_chars']
            
            ratio = real_context / real_code if real_code > 0 else 0
            status = "✅ Governed" if rule_count > 0 else "⚠️ Drift/Unmapped"
            
            f.write(f"| `{cf}` | {line_count} | {rule_count} | {real_code} | {real_context} | {ratio:.2f}x | {status} |\n")
            
            total_code += real_code
            total_context += real_context
            
        avg_ratio = total_context / total_code if total_code > 0 else 0
        f.write(f"\n## Global Metrics\n\n")
        f.write(f"- **Total Real Code Chars**: {total_code}\n")
        f.write(f"- **Total Real Context Chars**: {total_context}\n")
        f.write(f"- **Global Context-to-Code Ratio**: {avg_ratio:.2f}x\n")
        f.write(f"- **Governance Maturity**: {'High' if avg_ratio > 1.0 else 'Developing'}\n")

    print(f"✅ Report generated: {output_path}")

if __name__ == "__main__":
    main()
